import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./component/layers/Navbar";
import Footer from "./component/layers/Footer";
import {Darker_Grotesque,Roboto} from 'next/font/google'


const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${roboto.className}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
